num1 = complex(input('Enter the complex number 1: '))
num2 = complex(input('Enter the complex number 2: '))
print('Sum:', num1+num2)
num3 = float(input('Enter the float number 1: '))
num4 = float(input('Enter the float number 2: '))
print('Sum:', num3+num4)
num5 = int(input('Enter the integer number 1: '))
num6 = int(input('Enter the integer number 2: '))
print('Sum:', num5+num6)
